/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anh_com_opencvtest_DetectionUtil */

#ifndef _Included_anh_com_opencvtest_DetectionUtil
#define _Included_anh_com_opencvtest_DetectionUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anh_com_opencvtest_DetectionUtil
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_anh_com_opencvtest_DetectionUtil_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
