/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class anh_com_opencvtest_FaceDetection */

using namespace cv;
#ifndef _Included_anh_com_opencvtest_FaceDetection
#define _Included_anh_com_opencvtest_FaceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anh_com_opencvtest_FaceDetection
 * Method:    faceDetection
 * Signature: (J)V
 */

void detect(Mat& frame);
void processImages(Mat& frameOrigin, Mat& frame);

JNIEXPORT void JNICALL Java_anh_com_opencvtest_FaceDetection_faceDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     anh_com_opencvtest_FaceDetection
 * Method:    removeBG
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_anh_com_opencvtest_FaceDetection_removeBG
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif