/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "anh_com_opencvtest_FaceDetection.h"

extern "C"

JNIEXPORT void JNICALL Java_anh_com_opencvtest_FaceDetection_faceDetection
  (JNIEnv *, jclass, jlong addrRgba) {

}

